services:
  - type: web
    name: unistock
    env: docker
    plan: free
    rootDir: .
    preDeployCommand: php artisan migrate --seed --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-us-east-2.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.bmxfjvkrsvwrmnareljm
      - key: DB_PASSWORD
        value: 94410404Unilever
      - key: APP_KEY
        value: "base64:8Ehyg5VjdHSoqWmQG5o8gh8ucY9swIVvSi1aCZAWspw="
      - key: APP_URL
        value: https://unistock.onrender.com
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
